workflows:
  ios-app-store-release:
    name: iOS Native App Store Release
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: appcenter
    environment:
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.inuappcenter.unidorm
    scripts:
      - name: Resolve Swift Package Dependencies
        script: |
          xcodebuild -resolvePackageDependencies \
            -project "unidorm.xcodeproj" \
            -scheme "unidorm" \
            -derivedDataPath derived_data

      - name: Initialize Keychain & Fetch Signing Files
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "com.inuappcenter.unidorm" \
            --type IOS_APP_STORE \
            --create
          keychain add-certificates
          xcode-project use-profiles

      - name: Increment Build Number
        script: |
          agvtool new-version -all $(($BUILD_NUMBER + 12))

      - name: Build IPA for App Store
        script: |
          xcode-project build-ipa \
            --project "unidorm.xcodeproj" \
            --scheme "unidorm"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: false
        submit_to_app_store: false